const ACTIONS = {
    GET_USERS: "GET_USERS",
    SET_IS_LOADING_TRUE: "SET_IS_LOADING_TRUE",
    SET_IS_LOADING_FALSE: "SET_IS_LOADING_FALSE",
    CLEAR_USERS: "CLEAR_USERS"
}

export default ACTIONS;